---
- hosts: all
  user: root
  tasks:
  - name: Ensure FirewallD is installed
    yum:
      - name: firewalld
        state: present
      become: True
  - name: Ensure SSH can pass the firewall
    firewalld:
      service: ssh
      state: enabled
      permanent: True
      immediate: True
    become: True
  - name: Ensure FirewallD is running
    service:
      name: firewalld
      state: running
      enabled: True
    become: True
