---
- hosts: all
  user: root
  tasks:
    - name: Ensure libselinux-python is present
      yum:
        name: libselinux-python
        state: present
      become: True
    - name: Ensure libsemanage-python is present
      yum:
        name: libsemanage-python
        state: present
      become: True

